name: Move LeetCode Solutions

on:
  workflow_dispatch:
  push:
    paths:
      - '[0-9][0-9][0-9][0-9]-*/**'

jobs:
  move-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Align to latest origin/main (rebase)
        run: |
          git fetch origin main
          git checkout -B main
          git rebase origin/main

      - name: Move LeetCode solutions
        run: |
          set -e
          shopt -s nullglob
          mkdir -p LeetCode
          moved=0
          for d in [0-9][0-9][0-9][0-9]-*; do
            if [ -d "$d" ]; then
              git mv "$d" "LeetCode/" || mv "$d" "LeetCode/"
              moved=1
            fi
          done
          if [ $moved -eq 0 ]; then
            echo "No matching directories found to move"
          fi

      - name: Commit changes (if any)
        run: |
          if git status --porcelain | grep .; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: Move LeetCode solutions to LeetCode folder" || exit 0
          else
            echo "No changes to commit"
          fi

      - name: Rebase again on latest remote (guard)
        run: |
          git fetch origin main
          git rebase origin/main || (echo "Rebase conflict. Abort."; git rebase --abort; exit 1)

      - name: Push to main
        run: |
          git push origin HEAD:main